### ISSUE TITLE
Ability to specify the scope dynamically

### ISSUE THREAD

**Issue by orbanbotond** [walterhorstman/ordered-active-record#3]
I need this feature in case if a class can be a parent of itself (tree structures.)

**Comment by walterhorstman** [comment]
First of all, apologies for the long delay on this issue. Finally, I have some time (and personal needs) for this feature. Not having looked into this gem for awhile now, I might be mistaken, but as far as I known, it is possible to specify column names as scope and the positioning happens within the value of that column, so something like this should be possible: `acts_as_ordered(:position, scope: :parent_id)`.

Please let me know if I'm right or missing something. I'll try to answer a lot faster this time. :-)
