### ISSUE TITLE
Exception when saving a record with position not changed.

### ISSUE THREAD

**Issue by khustochka** [walterhorstman/ordered-active-record#5]
After upgrading to v0.9.9 I started getting an exception `LocalJumpError: unexpected return`.

It is caused by [this line](https://github.com/walterhorstman/ordered-active-record/commit/9f672ae62e0149ea9614ff2fd28234eea903ce60#diff-b5a29882a20d94a238c2aedcfed8bdabR14). Seems Rails does not like return from a before filter.

Also this was not covered with tests. Here is a failing test case:

```
    it('should not fail when position is not changed') do
      post = Post.create(text: 'Initial text', position: 1)
      post.update_attributes(text: "Changed text")
      expect(post.reload.position).to be(1)
    end
```

**Comment by walterhorstman** [comment]
Thanks for noticing this!
